# Generated by Django 2.0.3 on 2019-01-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('psswd', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transtype', models.CharField(choices=[('Credit', 'Cr'), ('Debut', 'Dr')], max_length=2)),
                ('amount', models.FloatField()),
                ('transtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(unique=True)),
                ('wname', models.CharField(max_length=100)),
                ('wamount', models.FloatField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackerapp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackerapp.Wallet'),
        ),
    ]
