# Generated by Django 2.0.3 on 2019-02-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_auto_20190120_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cid',
        ),
    ]
